### ISSUE TITLE
Cannot find ffmpeg

### ISSUE THREAD

**Issue by lester51** [furkaninanc/m3u8-to-mp4#7]
/data/data/io.tempage.dorynode/cache/node_modules/m3u8-to-mp4/index.js:50
          reject(new Error(error));
                 ^

Error: Error: Cannot find ffmpeg
    at FfmpegCommand.<anonymous> (/data/data/io.tempage.dorynode/cache/node_modules/m3u8-to-mp4/index.js:50:18)
    at FfmpegCommand.emit (node:events:527:28)
    at emitEnd (/data/data/io.tempage.dorynode/cache/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at /data/data/io.tempage.dorynode/cache/node_modules/fluent-ffmpeg/lib/processor.js:433:16
    at wrapper (/data/data/io.tempage.dorynode/cache/node_modules/async/dist/async.js:271:20)
    at next (/data/data/io.tempage.dorynode/cache/node_modules/async/dist/async.js:5795:24)
    at /data/data/io.tempage.dorynode/cache/node_modules/async/dist/async.js:327:20
    at wrapper (/data/data/io.tempage.dorynode/cache/node_modules/async/dist/async.js:271:20)
    at next (/data/data/io.tempage.dorynode/cache/node_modules/async/dist/async.js:5795:24)
    at /data/data/io.tempage.dorynode/cache/node_modules/async/dist/async.js:327:20

**Comment by ghost** [comment]
Here's how to fix it temporarily: https://stackoverflow.com/questions/45555960/nodejs-fluent-ffmpeg-cannot-find-ffmpeg
